username = input('Введите имя пользователя')
title = input('Введите заголовок заметки')
content = input('Введите описание заметки')
status = input('статус заметки')
created_date = input("Введите дату начала задачи в формате 20.12.2024")
issue_date = input("Введите дату завершения задачи в формате 22.12.2024")
print(f"Ваше имя пользователя: {username}")
print(f"Заголовок вашей заметки: {title}")
print(f"Описание заметки: {content}")
print(f"Статус заметки: {status}")
print(f"Дата начала задания: {created_date[0:6]}")
print(f"Дата завершения задания: {issue_date[0:6]}")
